version: "2.4"

services:
  # Log into this container with : docker-compose exec front sh
  front:
    env_file: .env
    build:
      context: ./docker/front
    container_name: front
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./docker/front/templates:/etc/nginx/templates
      - .:/home/docker:ro
    depends_on:
      - node

  # Log into this container with : docker-compose exec mongo /bin/bash
  # Use this command to log to the DB : mongo -u $MONGO_USERNAME -p $MONGO_USER_PASSWORD --authenticationDatabase $MONGO_INITDB_DATABASE
  mongo:
    env_file: .env
    image: mongo
    container_name: database
    restart: unless-stopped
    volumes:
      - database:/data/db
      - ./docker/mongo:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_USER_PASSWORD: ${MONGO_USER_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    command: --auth
    # Mongo display a lot of message in the log. For a better lisibility of the logs (especially for nodemon) disable the mongo logs
    logging:
      driver: "none"

  mongo-express:
    env_file: .env
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongo

  #  Log into this container with : docker-compose exec build sh
  node:
    env_file: .env
    build:
      context: ./docker/nodejs/
      args:
        # Get the user id & group id of the owner of the project dir with "ls -la" and paste the result here. This will update the
        # project dir permission inside the container
        - HOST_USER=${HOST_USER}
        - HOST_USERGROUP=${HOST_USERGROUP}
    restart: unless-stopped
    container_name: node
    volumes:
      - ./:/home/docker:rw
    command: "npm run dev --prefix server"

volumes:
  database: {}
